# Generated by Django 2.0.5 on 2018-06-24 18:33

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0007_auto_20180624_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_test.City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=smart_selects.db_fields.ChainedForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_test.Country'),
        ),
    ]
