# Generated by Django 2.0.5 on 2018-07-04 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_test', '0016_auto_20180624_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_amount', models.IntegerField(choices=[(0, '5'), (1, '10'), (2, '15'), (3, '20'), (4, '25'), (5, '30')], default=0)),
                ('question_level', models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0)),
                ('question_type', models.IntegerField(choices=[(0, 'Multiple Chioce'), (1, 'True/False'), (2, 'Any Type')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Completed')], default=0)),
                ('question_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_test.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
