# Generated by Django 2.0.5 on 2018-07-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0018_auto_20180704_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='session',
            field=models.IntegerField(default=0),
        ),
    ]
