# Generated by Django 2.0.5 on 2018-07-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0020_auto_20180704_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='q_type',
            field=models.IntegerField(choices=[(0, 'Multiple Choice'), (1, 'True/False'), (2, 'Any Type')], default=0),
        ),
    ]
