# Generated by Django 2.0.5 on 2018-07-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0022_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='level',
            field=models.IntegerField(choices=[(0, 'easy'), (1, 'medium'), (2, 'hard')], default=0),
        ),
    ]
