# Generated by Django 2.0.5 on 2018-07-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0023_auto_20180705_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
